version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - LAMINI_API_KEY=${LAMINI_API_KEY}

volumes:
  postgres_data:
